apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
      - name: brain-app
        image: 978823451478.dkr.ecr.ap-south-1.amazonaws.com/brain-app:latest
        ports:
        - containerPort: 80

